export const constants = {
  youtubeApiUrl: "https://www.googleapis.com/youtube/v3/search",
  queryTags: [
    "javascript tutorial",
    "python tutorial",
    "java tutorial",
    "c++ tutorial",
    "c# tutorial",
    "php tutorial",
    "ruby tutorial",
    "go tutorial",
    "kotlin tutorial",
    "swift tutorial",
    "typescript tutorial",
    "full-stack-development tutorial",
    "machine-learning tutorial",
    "data-science tutorial",
    "artificial-intelligence tutorial",
    "web-development tutorial",
    "mobile-development tutorial",
    "cloud-computing tutorial",
    "cybersecurity tutorial",
    "devops tutorial",
    "blockchain tutorial",
    "internet-of-things tutorial",
  ],
};
