export const constants = {
  topics: [
    "javascript",
    "python",
    "java",
    "c++",
    "c#",
    "php",
    "ruby",
    "go",
    "kotlin",
    "swift",
    "typescript",
    "full-stack-development",
    "machine-learning",
    "data-science",
    "artificial-intelligence",
    "web-development",
    "mobile-development",
    "cloud-computing",
    "cybersecurity",
    "devops",
    "blockchain",
    "internet-of-things",
  ],
  level: ["low", "medium", "high"],
};
